services:
  uniclique-db:
    image: postgres:15
    container_name: uniclique-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: uniclique_user
      POSTGRES_PASSWORD: uniclique_pass_123
      POSTGRES_DB: uniclique_db
    ports:
      - "5432:5432"
    volumes:
      - uniclique_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uniclique_user -d uniclique_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  uniclique-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uniclique-api
    restart: unless-stopped
    depends_on:
      uniclique-db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=uniclique-db;Port=5432;Database=uniclique_db;Username=uniclique_user;Password=uniclique_pass_123"
    ports:
      - "5050:8080"  # dış port 5050 oldu

volumes:
  uniclique_pg_data:
