version: "3.9"

services:
  uniclique-db:
    image: postgres:15
    container_name: uniclique-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: uniclique_db
      POSTGRES_USER: uniclique_user
      POSTGRES_PASSWORD: uniclique_pass

    ports:
      - "5432:5432"

    volumes:
      - uniclique_pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uniclique_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  uniclique_pgdata:
